title: Time never stops
author: anmolkumar007
email: anmolk2106@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  no one can describe **time**

# social links
twitter_username: anmolk2106 # DO NOT include the @ character, or else the build will fail!
github_username:  anmolkumar007 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
